#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;
use Illuminate\Contracts\Console\Kernel;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
$app = require_once __DIR__.'/bootstrap/app.php';

$kernel = $app->make(Kernel::class);

$status = 0;

try {
    $status = $kernel->handle(
        new ArgvInput,
        new ConsoleOutput
    );
} catch (Exception $e) {
    $kernel->reportException($e);
    $kernel->renderException($e, new ConsoleOutput);
    $status = 1;
}

exit($status);
